FROM tomcat:8.0
MAINTAINER "bucketzxm <bucketzxm@gmail.com>"

ENV CATALINA_BASE:   /usr/local/tomcat
ENV CATALINA_HOME:   /usr/local/tomcat
ENV CATALINA_TMPDIR: /usr/local/tomcat/temp
ENV JRE_HOME:        /usr
ENV CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar

#ADD conf/tomcat-users.xml $CATALINA_HOME/conf
#ADD conf/server.xml $CATALINA_HOME/conf
#ADD conf/web.xml $CATALINA_HOME/conf