version: "3"

services:
  redis:
    image:  redis:3.2.8
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node == node1
  mysql:
    image: mysql:5.6.35
    networks:
      - yunborapp
    ports:
      - "3306:3306"
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node == node1
  nginx:
    image: nginx:latest
    networks:
      - yunborapp
    deploy:
      placement:
        constraints:
          - node.role == manager

  tomcat:
    image: tomcat:8.0
    networks:
      - yunborapp
    deploy:
      placement:
        constraints:
          - node.role == worker
          - node = node2

networks:
  yunborapp:


volumes:
  mysql-data:
